# Generated by Django 3.0.2 on 2020-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='daily_email',
            field=models.BooleanField(default=False),
        ),
    ]
