# Generated by Django 2.0 on 2018-01-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20180110_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='date completed'),
        ),
    ]
