# Generated by Django 2.0 on 2018-03-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_edit_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='last edit date'),
        ),
    ]
