# Generated by Django 2.0 on 2018-06-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_task_snooze_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('A', 'High'), ('B', 'Normal'), ('C', 'Low')], default='C', max_length=1, verbose_name='priority'),
        ),
    ]
